use_frameworks!
source 'https://github.com/a550482560/BSCMSpec.git'

platform :ios, '9.0'

target 'BSRouter_Example' do
  pod 'BSRouter', :path => '../'
  pod 'HomePage','~> 6.6.8'
  pod 'MineVC','~> 6.6.8'
end
